# Generated by Django 4.1.2 on 2022-10-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=500)),
                ('courseSummary', models.CharField(max_length=500)),
                ('courseImage', models.CharField(max_length=500)),
                ('courseDate', models.DateField()),
            ],
        ),
    ]
